/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votingmgmtsystem;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
/**
 *
 * @author sanjeev kumar
 */
public class MainForm extends javax.swing.JFrame {

      Connection con;
    PreparedStatement pt;
    ResultSet rs;
    Statement st;
    String U="Active";
     
    public MainForm() {
        initComponents();
        setconnection();
         DateFormat df = new SimpleDateFormat("dd/MM/YYYY");
        java.util.Date dateobj = new java.util.Date();
        lbldate.setText(df.format(dateobj));
        disable();
    }
     public void setconnection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VotingSystem", "root", "");
            st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            System.out.println("connected");
             Status(); Status1(); Status2();
        } catch (Exception e) {
            System.out.println("Error in Connection plz Check :" + e);
        }
    }
      public void Status()
    {
         try{
            rs=st.executeQuery("select * from condidateregistration where Status='"+U+"'");
           rs.next();
            lblid.setText(rs.getString(1));
        }catch(Exception ex){}
    }
      public void Status1()
    {
         try{
              rs=st.executeQuery("select * from voterregistration  where Status='"+U+"'");
              rs.next();
              lblid1.setText(rs.getString(1));
        }catch(Exception ex){}
    }
        public void Status2()
    {
         try{
              rs=st.executeQuery("select * from login  where Status='"+U+"'");
              rs.next();
              lblid2.setText(rs.getString(1));
        }catch(Exception ex){}
    }
        public void disable()
        {
            if(lblid.getText().equals("")&&lblid1.getText().equals("")&&lblid2.getText().equals(""))
            {
               Mvoting.setVisible(true);
               Mfile.setVisible(false);
               Medit.setVisible(false);
                Mhistory.setVisible(false);
               Mdetail.setVisible(false);
               Mabout.setVisible(false);
               Msetting.setVisible(false);
               Mv1.setVisible(false);
            }
            else if(lblid.getText().equals("")&&lblid1.getText().equals(""))
            {
                
                
            }
            else if(lblid.getText().equals(""))
            {
               MCR.setVisible(false);
                Mdetail.setVisible(false);
                Mhistory.setVisible(false);
                MCU.setVisible(false);
                MCD.setVisible(false);
                Mv1.setVisible(false);
                
            }
             else
            {
                MVR.setVisible(false);
                Mdetail.setVisible(false);
                Mhistory.setVisible(false);
                MVU.setVisible(false);
                MVD.setVisible(false); 
                Mv1.setVisible(false);
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgbox = new javax.swing.JOptionPane();
        lblid = new javax.swing.JLabel();
        lblid1 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        lblid2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Mfile = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        MVR = new javax.swing.JMenuItem();
        MCR = new javax.swing.JMenuItem();
        Medit = new javax.swing.JMenu();
        MVU = new javax.swing.JMenuItem();
        MCU = new javax.swing.JMenuItem();
        MVD = new javax.swing.JMenuItem();
        MCD = new javax.swing.JMenuItem();
        Mvoting = new javax.swing.JMenu();
        Madhar = new javax.swing.JMenuItem();
        Mfinger = new javax.swing.JMenuItem();
        Mcal = new javax.swing.JMenuItem();
        Mabout = new javax.swing.JMenu();
        Mabout1 = new javax.swing.JMenuItem();
        Mdetail = new javax.swing.JMenu();
        MCDetail = new javax.swing.JMenuItem();
        MVDetail = new javax.swing.JMenuItem();
        Mvotes = new javax.swing.JMenuItem();
        Msetting = new javax.swing.JMenu();
        Msett = new javax.swing.JMenuItem();
        Mv1 = new javax.swing.JMenu();
        Mv = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Mhistory = new javax.swing.JMenu();
        MH = new javax.swing.JMenuItem();
        Mexit = new javax.swing.JMenu();
        ME = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VOTING SYSTEM");

        lblid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblid1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbllogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(0, 0, 255));
        lbllogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/votingmgmtsystem/exit.png"))); // NOI18N
        lbllogout.setText("LogOut");
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoutMouseClicked(evt);
            }
        });

        lblid2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/votingmgmtsystem/architectural-81a - Copy.jpg"))); // NOI18N

        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Mfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Mfile.setText("File     ");
        Mfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenu1.setText("New");

        MVR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        MVR.setText("Voter Registration ");
        MVR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MVRActionPerformed(evt);
            }
        });
        jMenu1.add(MVR);

        MCR.setText("Candidate Registration");
        MCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCRActionPerformed(evt);
            }
        });
        jMenu1.add(MCR);

        Mfile.add(jMenu1);

        Menu.add(Mfile);

        Medit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Medit.setText("Editing");
        Medit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MVU.setText("Voter Update");
        MVU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MVUActionPerformed(evt);
            }
        });
        Medit.add(MVU);

        MCU.setText("Candidate Update");
        MCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCUActionPerformed(evt);
            }
        });
        Medit.add(MCU);

        MVD.setText("Voter Delete");
        MVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MVDActionPerformed(evt);
            }
        });
        Medit.add(MVD);

        MCD.setText("Candidate Delete");
        MCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCDActionPerformed(evt);
            }
        });
        Medit.add(MCD);

        Menu.add(Medit);

        Mvoting.setText("Voting");
        Mvoting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Madhar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        Madhar.setText("For Adhar Card");
        Madhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MadharActionPerformed(evt);
            }
        });
        Mvoting.add(Madhar);

        Mfinger.setText("For Finger Print");
        Mfinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MfingerActionPerformed(evt);
            }
        });
        Mvoting.add(Mfinger);

        Mcal.setText("Calculate");
        Mcal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                McalActionPerformed(evt);
            }
        });
        Mvoting.add(Mcal);

        Menu.add(Mvoting);

        Mabout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Mabout.setText("  About Us");
        Mabout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Mabout1.setText("About ");
        Mabout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mabout1ActionPerformed(evt);
            }
        });
        Mabout.add(Mabout1);

        Menu.add(Mabout);

        Mdetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Mdetail.setText("    Details");
        Mdetail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MCDetail.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        MCDetail.setText("Candidate Detail");
        MCDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCDetailActionPerformed(evt);
            }
        });
        Mdetail.add(MCDetail);

        MVDetail.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, 0));
        MVDetail.setText("Voter Detail");
        MVDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MVDetailActionPerformed(evt);
            }
        });
        Mdetail.add(MVDetail);

        Mvotes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Mvotes.setText("Votes");
        Mvotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MvotesActionPerformed(evt);
            }
        });
        Mdetail.add(Mvotes);

        Menu.add(Mdetail);

        Msetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Msetting.setText("   Setting");
        Msetting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Msett.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Msett.setText("Setting");
        Msett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsettActionPerformed(evt);
            }
        });
        Msetting.add(Msett);

        Menu.add(Msetting);

        Mv1.setText("VerifyAdhar");
        Mv1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Mv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        Mv.setText("VerifyAdhar");
        Mv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MvActionPerformed(evt);
            }
        });
        Mv1.add(Mv);

        Menu.add(Mv1);

        jMenu2.setText("   Mail    ");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        Menu.add(jMenu2);

        Mhistory.setText("History");
        Mhistory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Mhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MhistoryActionPerformed(evt);
            }
        });

        MH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        MH.setText("history");
        MH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MHActionPerformed(evt);
            }
        });
        Mhistory.add(MH);

        Menu.add(Mhistory);

        Mexit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Mexit.setText("     Exit");
        Mexit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        ME.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        ME.setText("Exit");
        ME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEActionPerformed(evt);
            }
        });
        Mexit.add(ME);

        Menu.add(Mexit);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243)
                .addComponent(lblid1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblid2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbllogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllogout)
                            .addComponent(lblid1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblid2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseClicked
        // TODO add your handling code here:
        String id1=lblid1.getText();
        String id=lblid.getText();
        String id2=lblid2.getText();
        try{
            pt = con.prepareStatement("update voterregistration set Status=? where Id='"+id1+"'");
            pt.setString(1, "LogOut");
            pt.executeUpdate();
            pt = con.prepareStatement("update condidateregistration set Status=? where Id='"+id+"'");
            pt.setString(1, "LogOut");
            pt.executeUpdate();
            pt = con.prepareStatement("update login set Status=? where username='"+id2+"'");
            pt.setString(1, "LogOut");
            pt.executeUpdate();
           msgbox.showMessageDialog(null,"LogOut Scussefull");
           new Login().setVisible(true);
           this.dispose();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_lbllogoutMouseClicked

    private void MhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MhistoryActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_MhistoryActionPerformed

    private void MHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MHActionPerformed
        // TODO add your handling code here:
         new HistoryGrid().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MHActionPerformed

    private void MCDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCDetailActionPerformed
        // TODO add your handling code here:
        new CandidateGrid().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MCDetailActionPerformed

    private void MVDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MVDetailActionPerformed
        // TODO add your handling code here:
         new VoterGrid().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MVDetailActionPerformed

    private void MVRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MVRActionPerformed
        // TODO add your handling code here:
        new VoterRegistration().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MVRActionPerformed

    private void MCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCRActionPerformed
        // TODO add your handling code here:
         new CandidateRegistration().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MCRActionPerformed

    private void MCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCDActionPerformed
        // TODO add your handling code here:
        new DeleteCandidate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MCDActionPerformed

    private void MfingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MfingerActionPerformed
        // TODO add your handling code here:
        new VerifyAdhar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MfingerActionPerformed

    private void MadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MadharActionPerformed
        // TODO add your handling code here:
        new AdharVarify().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MadharActionPerformed

    private void MEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEActionPerformed
        // TODO add your handling code here:
         String id1=lblid1.getText();
        String id=lblid.getText();
        String id2=lblid2.getText();
        try{
            pt = con.prepareStatement("update voterregistration set Status=? where Id='"+id1+"'");
            pt.setString(1, "LogOut");
            pt.executeUpdate();
            pt = con.prepareStatement("update condidateregistration set Status=? where Id='"+id+"'");
            pt.setString(1, "LogOut");
            pt.executeUpdate();
            pt = con.prepareStatement("update login set Status=? where username='"+id2+"'");
            pt.setString(1, "LogOut");
            pt.executeUpdate();
            this.dispose();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_MEActionPerformed

    private void MVUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MVUActionPerformed
        // TODO add your handling code here:
        new VoterUpdate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MVUActionPerformed

    private void MCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCUActionPerformed
        // TODO add your handling code here:
        new CandidateUpdate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MCUActionPerformed

    private void MVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MVDActionPerformed
        // TODO add your handling code here
        new DeleteVoter().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MVDActionPerformed

    private void MsettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsettActionPerformed
        // TODO add your handling code here:
        new Setting().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MsettActionPerformed

    private void MvotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MvotesActionPerformed
        // TODO add your handling code here:
        
        new ShowVotes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MvotesActionPerformed

    private void McalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_McalActionPerformed
        // TODO add your handling code here:
        new Counting().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_McalActionPerformed

    private void Mabout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mabout1ActionPerformed
        // TODO add your handling code here:
        new aboutus().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Mabout1ActionPerformed

    private void MvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MvActionPerformed
        // TODO add your handling code here:
        new VerifyAdhar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MvActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MCD;
    private javax.swing.JMenuItem MCDetail;
    private javax.swing.JMenuItem MCR;
    private javax.swing.JMenuItem MCU;
    private javax.swing.JMenuItem ME;
    private javax.swing.JMenuItem MH;
    private javax.swing.JMenuItem MVD;
    private javax.swing.JMenuItem MVDetail;
    private javax.swing.JMenuItem MVR;
    private javax.swing.JMenuItem MVU;
    private javax.swing.JMenu Mabout;
    private javax.swing.JMenuItem Mabout1;
    private javax.swing.JMenuItem Madhar;
    private javax.swing.JMenuItem Mcal;
    private javax.swing.JMenu Mdetail;
    private javax.swing.JMenu Medit;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Mexit;
    private javax.swing.JMenu Mfile;
    private javax.swing.JMenuItem Mfinger;
    private javax.swing.JMenu Mhistory;
    private javax.swing.JMenuItem Msett;
    private javax.swing.JMenu Msetting;
    private javax.swing.JMenuItem Mv;
    private javax.swing.JMenu Mv1;
    private javax.swing.JMenuItem Mvotes;
    private javax.swing.JMenu Mvoting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblid1;
    private javax.swing.JLabel lblid2;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JOptionPane msgbox;
    // End of variables declaration//GEN-END:variables
}
